---
name: Build and Deploy site
# run-name: Build site with mkdocs and deploy on github pages.
on:
  push:
    branches:
      - main
env:
  SITE_DIR: "_site"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "${{ github.repository }}/requirements.txt"
      - name: Build site
        id: build
        run: |
          mkdocs build --site-dir ../${{ github.repository }}/$SITE_DIR -f ${{ github.repository }}/mkdocs/mkdocs.yml
      - name: Archive Site
        run: |
          tar \
            --dereference --hard-dereference \
            --directory "${{ github.repository }}/$SITE_DIR" \
            -cvf ${{ github.repository }}/artifact.tar \
            .
      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "${{ github.repository }}/artifact.tar"
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

