site_name: Rafael Prata
site_url: https://rafaprata.github.io
theme:
  name: material
  palette: 
        # Palette toggle for light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: cyan

    # Palette toggle for dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/brightness-4
        name: Switch to system mode
      primary: cyan

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
  font:
    text: Kadwa
    code: Sometype Mono
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.footer
    - navigation.tracking
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - toc.integrate
  # icon:
  #   logo: :fontawesome-solid-fire-flame-curved:

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# nav:
#   - Home: 
#       - index.md
#       - test.md
#   - Test: test2.md

extra:
  generator: false

copyright: "Copyright &copy; 2022 - 2024 Rafael Prata"

plugins:
  - blog:
      enabled: true
      blog_dir: .
      blog_toc: true
      post_dir: "{blog}/posts"
      # post_url_max_categories: 1
      # post_slugify_separator: "-"
      # post_excerpt_max_authors: 1
      # post_excerpt_max_categories: 5
      # post_excerpt_separator: <!-- more -->
      # post_readtime: true
      # post_readtime_words_per_minute: 265
      archive: false
      # archive_name: Archive
      # archive_pagination: true
      # archive_pagination_per_page: 10
      # archive_toc: false
      categories: false
      # categories_name: Categories
      # categories_slugify_separator: "-"
      # categories_pagination: true
      # categories_pagination_per_page: 10
      # categories_toc: false
      authors: true
      authors_file: "{blog}/.authors.yml"
      # authors_profiles: false
      # authors_profiles_name: Authors
      # authors_profiles_pagination: true
      # authors_profiles_pagination_per_page: 10
      # authors_profiles_toc: false
      pagination: true
      pagination_per_page: 2
      pagination_keep_content: false
      # draft: false
      # draft_on_serve: true
      # draft_if_future_date: false